### ISSUE TITLE
kachery resource daemon dies and does not always restart

### ISSUE THREAD

**Issue by lfrank** [scratchrealm/kachery-resource#5]
leaving the 

`npx kachery-resource@latest share `

running eventually yielded:

```
Disconnected. Will try again in 30 seconds.
Connecting to https://kachery-resource-proxy.herokuapp.com
Connected
Connection acknowledged by proxy server

Resource URL: https://kachery-resource-proxy.herokuapp.com/r/franklab.default

Websocket closed.
Disconnected. Will try again in 30 seconds.
Connecting to https://kachery-resource-proxy.herokuapp.com
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at connResetException (node:internal/errors:705:14)
    at TLSSocket.socketOnEnd (node:_http_client:518:23)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (/home/loren/.npm/_npx/ec1da2ed9351c0ff/node_modules/ws/lib/websocket.js:1008:13)
    at ClientRequest.<anonymous> (/home/loren/.npm/_npx/ec1da2ed9351c0ff/node_modules/ws/lib/websocket.js:856:5)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketOnEnd (node:_http_client:518:9)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET'
}

```

**Comment by lfrank** [comment]
This may have been a problem on my end; I'll reopen if not.
